spring.application.name=api
# Порт сервера
server.port=8080

# Подключение к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/moodvoice_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Настройки создания таблиц
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true